pipeline:
  test_client:
    group: test
    image: node:10-alpine
    commands:
      - yarn --cwd client install
      - CI=true yarn --cwd client run react-scripts test --env=jsdom

  lint_js:
    group: test
    image: node:10-alpine
    commands:
      - yarn install
      # We should probably install recursively so we can check dependencies
      # properly...
      - yarn run ci-lint

  build_prod_client:
    image: plugins/docker
    when:
      branch: master
      event: push
    registry: registry.6gu.nz
    repo: registry.6gu.nz/client
    tags: latest
    context: client
    dockerfile: client/Dockerfile-prod
    group: build
    secrets: [ docker_username, docker_password ]

  build_prod_api:
    image: plugins/docker
    when:
      branch: master
      event: push
    registry: registry.6gu.nz
    repo: registry.6gu.nz/api
    tags: latest
    context: api
    dockerfile: api/Dockerfile-prod
    group: build
    secrets: [ docker_username, docker_password ]

  deploy_staging:
    when:
      branch: master
      event: push
    image: appleboy/drone-ssh
    host: staging.6gu.nz
    username: root
    key_path: /root/ssh/drone_rsa
    volumes:
      - /root/.ssh/staging_server_key:/root/ssh/drone_rsa
    script:
      - cd /root/6gu/machines
      - bash run.sh everything
