version: "3"
services:
  client:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - './client:/app'
      - '/app/node_modules'

  api:
    build: ./api
    restart: on-failure
    ports:
      - '3001:3001'
    volumes:
      - './api:/app'
      - '/app/node_modules'
    env_file:
      - .env

  fake_oauth_server:
    build: ./fakeOauthServer
    restart: on-failure
    ports:
      - '2999:2999'
    environment:
      HOST: ${HOST}
    volumes:
      - './fakeOauthServer:/app'
      - '/app/node_modules'

  database:
    image: postgres:10
    restart: on-failure
    ports:
      - '5432'
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - './postgres/init:/docker-entrypoint-initdb.d'
      # Consider linking this volume into the postgres directory so it doesn't
      # get destroyed when we `docker-compose down`.
      - '/var/lib/postgresql/data'
