#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

if [ "$#" -ne 1 ]; then
  echo "Please specify one parameter -- migration name"
  exit
fi

yarn --cwd api migrate --template-file api/src/migration-template.js "$1"
