# (Dev) Just install packages, we get the source code from the volume mount.
FROM node:10

WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn

COPY src ./src
CMD ["yarn", "nodemon", "src/server.js"]
