# (Dev) Just install packages, we get the source code from the volume mount.
FROM node:10

WORKDIR /app
COPY package.json yarn.lock ./
RUN NODE_ENV=production yarn

COPY src ./src
COPY migrations ./migrations
CMD ["node", "src/server.js"]
